// Copies the Ultraviolet + Scramjet + bare-mux + epoxy transport client bundles
// out of node_modules into public/ so Express can serve them as static assets.
// The proxy client (service worker / shared worker), rewriter, and config must
// all be same-origin with the page that registers them.
//
// Run with: npm run build:uv

import { cp, mkdir, rm, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { existsSync } from "node:fs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const nm = join(root, "node_modules");

const targets = [
  { name: "Ultraviolet bundle", from: "@titaniumnetwork-dev/ultraviolet/dist", to: "public/uv", required: true },
  { name: "bare-mux client", from: "@mercuryworkshop/bare-mux/dist", to: "public/baremux", required: true },
  { name: "epoxy transport", from: "@mercuryworkshop/epoxy-transport/dist", to: "public/epoxy", required: true },
  { name: "Scramjet bundle", from: "@mercuryworkshop/scramjet/dist", to: "public/scramjet", required: false },
  { name: "libcurl transport", from: "@mercuryworkshop/libcurl-transport/dist", to: "public/libcurl", required: false },
];

let failed = false;

for (const t of targets) {
  const fromPath = join(nm, t.from);
  const toPath = join(root, t.to);
  if (!existsSync(fromPath)) {
    if (t.required) {
      console.error(`X ${t.name}: source not found at ${fromPath}`);
      failed = true;
    } else {
      console.log(`· ${t.name}: skipped (not installed; engine toggle will offer UV only)`);
    }
    continue;
  }
  await rm(toPath, { recursive: true, force: true });
  await mkdir(toPath, { recursive: true });
  await cp(fromPath, toPath, { recursive: true });
  console.log(`OK ${t.name}: ${t.from} -> ${t.to}`);
}

// epoxy-tls wasm + glue lives in a sibling package. Copy its "full" build
// (includes a bundled TLS impl) into public/epoxy/.
const epoxyTlsFull = join(nm, "@mercuryworkshop/epoxy-tls/full");
if (existsSync(epoxyTlsFull)) {
  const dest = join(root, "public/epoxy");
  for (const f of ["epoxy-bundled.js", "epoxy.wasm"]) {
    await cp(join(epoxyTlsFull, f), join(dest, f), { recursive: true });
  }
  console.log("OK epoxy-tls (full): wasm + bundled glue -> public/epoxy/");
} else {
  console.warn("! epoxy-tls not found — proxied HTTPS sites will fail. Install @mercuryworkshop/epoxy-tls.");
}

// Rewrite uv.config.js so handler/client/bundle/config/sw paths point at /uv/.
const uvConfigPath = join(root, "public/uv/uv.config.js");
if (existsSync(uvConfigPath)) {
  let cfg = await readFile(uvConfigPath, "utf8");
  cfg = cfg
    .replace("'/uv.handler.js'", "'/uv/uv.handler.js'")
    .replace("'/uv.client.js'", "'/uv/uv.client.js'")
    .replace("'/uv.bundle.js'", "'/uv/uv.bundle.js'")
    .replace("'/uv.config.js'", "'/uv/uv.config.js'")
    .replace("'/uv.sw.js'", "'/uv/uv.sw.js'");
  await writeFile(uvConfigPath, cfg);
  console.log("OK rewrote uv.config.js paths -> /uv/*");
}

// Make uv.sw.js self-contained AND wire its fetch handler. The npm package's
// uv.sw.js (a) opens with `var h = self.Ultraviolet`, which is undefined in the
// isolated SW scope unless we importScripts the bundle, and (b) defines
// self.UVServiceWorker as a class but never instantiates it or attaches a
// fetch listener. The canonical Ultraviolet-App has a separate sw.js that does
// both. We prepend importScripts and append the instantiation + listener.
const uvSwPath = join(root, "public/uv/uv.sw.js");
if (existsSync(uvSwPath)) {
  let swSrc = await readFile(uvSwPath, "utf8");
  if (!swSrc.startsWith("importScripts")) {
    const wiring =
      'importScripts("/uv/uv.bundle.js", "/uv/uv.config.js");\n' +
      swSrc +
      '\n// Wire the fetch handler (appended by build-uv.mjs).\n' +
      'const uvSW = new self.UVServiceWorker();\n' +
      'self.addEventListener("fetch", (event) => {\n' +
      '  if (uvSW.route({ request: event.request })) {\n' +
      '    event.respondWith(uvSW.fetch({ request: event.request }));\n' +
      '  }\n' +
      '});\n';
    await writeFile(uvSwPath, wiring);
    console.log("OK made uv.sw.js self-contained + wired fetch handler");
  }
}

if (failed) {
  console.error("\nBuild failed. Run `npm install` first.");
  process.exit(1);
}

// Write the Scramjet service worker into public/scramjet/ (the recursive copy
// above only pulls files from the npm package, which does not ship an sw.js).
// clients.claim() is critical: without it, a freshly-registered SW does not
// control the existing page until the next navigation, so /scramjet/* requests
// fell through to Express 404. This was the real Scramjet blocker.
const scramjetSw = join(root, "public/scramjet/sw.js");
await writeFile(
  scramjetSw,
  `// Scramjet service worker. Generated by scripts/build-uv.mjs.
importScripts("/scramjet/scramjet.all.js");
const { ScramjetServiceWorker } = $scramjetLoadWorker();
const scramjet = new ScramjetServiceWorker();
async function handleRequest(event) {
  await scramjet.loadConfig();
  if (scramjet.route(event)) return scramjet.fetch(event);
  return fetch(event.request);
}
self.addEventListener("fetch", (event) => {
  event.respondWith(handleRequest(event));
});
self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});
`
);
console.log("OK wrote public/scramjet/sw.js");

console.log("\nClient bundles ready. Start the server: npm start");
